input {
  beats {
    port => 5044
    ssl_enabled => true
    ssl_certificate => "/usr/share/logstash/config/beats-tls/cert.pem"
    ssl_key => "/usr/share/logstash/config/beats-tls/key.pkcs8.pem"
    ssl_certificate_authorities => ["/usr/share/logstash/config/beats-tls/ca.crt"]
    ssl_client_authentication => "required"
    event_loop_threads => 2
    executor_threads => 2
  }
}
filter {
  if [fields][lab_source] == "linux" {
    mutate { add_field => { "[@metadata][target_index]" => "observabilite-linux" } }
  } else if [fields][lab_source] == "windows" {
    mutate { add_field => { "[@metadata][target_index]" => "observabilite-windows" } }
  } else {
    drop { }
  }
}
output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"]
    api_key => "${LOGSTASH_LOGS_API_KEY}"
    ssl_enabled => true
    ssl_certificate_authorities => ["/usr/share/logstash/config/certs/http_ca.crt"]
    index => "%{[@metadata][target_index]}"
    action => "create"
    data_stream => false
    ilm_enabled => false
    manage_template => false
  }
}
