input {
  generator {
    message => "TEST_LAB_OBSERVABILITE"
    count => 1
  }
}

output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"]
    api_key => "${LOGSTASH_API_KEY}"
    ssl_enabled => true
    ssl_certificate_authorities => ["/usr/share/logstash/config/certs/http_ca.crt"]
    index => "observabilite-test"
    action => "create"
    data_stream => false
    ilm_enabled => false
    manage_template => false
  }
  stdout { codec => rubydebug }
}
